import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import { Providers } from "./providers";

import { Topbar } from "./_components/Topbar";

interface RootLayoutProps {
  children: React.ReactNode;
  landing: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: RootLayoutProps) {
  const headersList = headers();
  const activePath = headersList.get("x-invoke-path");
  console.log("LANDING", props.landing);
  return (
    <html lang="en">
      <body
        className={`dark text-foreground bg-background min-h-screen ${inter.className}`}
      >
        <Providers>
          <Topbar pathname={activePath} />
          {activePath === "/" ? props.landing : props.children}
        </Providers>
      </body>
    </html>
  );
}
